title: "Гильдия Ясный Лес @ EU Галакронд"
description: >- # this means to ignore newlines until "baseurl:"
  Гильдия Ясный Лес, World of Warcraft, EU Галакронд.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://forestguild.club" # the base hostname & protocol for your site, e.g. http://example.com
repository: rakshazi/forestguild.club
realm: galakrond
disqus: forestguild
links:
  - name: Discord
    url: https://discord.gg/v9mNxAS
    class: text-danger
  - name: Оружейная
    url: https://eu.battle.net/wow/ru/guild/galakrond/Ясный_Лес/
    class:
  - name: WoWProgress
    url: https://www.wowprogress.com/guild/eu/галакронд/Ясный+Лес
    class:
  - name: Raider.IO
    url: https://raider.io/guilds/eu/galakrond/Ясный%20Лес
    class:

rt:
  active: false
  date: "Среда и четверг 19:00-21:00 МСК "
  description: "В 19:00 уже заходим в рейд, приходить в дискорд нужно за 20-30 минут до начала."
  setup:
    default: "2 / 4 / 14"
    modifiable: true
  requirements:
    ilvl: 340
    flasks: 2
  raid: "Ульдир"

# Build settings
markdown: kramdown
compress_html:
  clippings: all
  comments: all
  startings: all
  endings: all
  blanklines: false
  profile: false
exclude:
  - README.md
  - Makefile
  - Gemfile
  - Gemfile.lock
  - updater
  - updater.php
  - .php_cs.dist
  - .travis.yml
